package org.ujorm.petstore.utilities;

import org.ujorm.orm.SqlQuery;

import java.sql.Connection;

/**
 * Initial database setup and schema generation
 */
public class InitDatabase {

    /**
     * Creates database tables if not already initialized
     */
    public void createTables(Connection connection) {
        changeset_01(connection);
    }

    /**
     * Executes DDL and initial DML scripts using standard SQL identity syntax
     */
    private void changeset_01(Connection connection) {
        try (var query = new SqlQuery(connection)) {

            var count = query.sql("""
                    SELECT 1 FROM information_schema.tables
                    WHERE LOWER(table_name) = 'employee'
                      AND LOWER(table_schema) IN ('public', 'public')
                    LIMIT 1
                    """).toStream(rs -> rs).count();
            if (count > 0) {
                return;
            }

            query.sql("""
                    CREATE TABLE employee (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL
                    )
                    """).execute();

            query.sql("""
                    CREATE TABLE category (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL
                    )
                    """).execute();

            query.sql("""
                    CREATE TABLE customer (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL
                    )
                    """).execute();

            query.sql("""
                    CREATE TABLE pet (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL,
                        status VARCHAR(50) NOT NULL,
                        category_id BIGINT NOT NULL,
                        CONSTRAINT fk_pet_category FOREIGN KEY (category_id) REFERENCES category(id)
                    )
                    """).execute();

            query.sql("""
                    CREATE TABLE pet_order (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        customer_id BIGINT NOT NULL,
                        pet_id BIGINT NOT NULL,
                        CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE CASCADE,
                        CONSTRAINT fk_order_pet FOREIGN KEY (pet_id) REFERENCES pet(id) ON DELETE CASCADE
                    )
                    """).execute();

            // Initial data
            query.sql("INSERT INTO category (name) VALUES ('Dogs')").execute();
            query.sql("INSERT INTO category (name) VALUES ('Cats')").execute();
            query.sql("INSERT INTO category (name) VALUES ('Birds')").execute();

            query.sql("INSERT INTO customer (id, name) VALUES (1, 'John Doe')").execute();

            query.sql("""
                    INSERT INTO pet (name, status, category_id) VALUES
                    ('Rex', 'AVAILABLE', 1),
                    ('Buddy', 'PENDING', 1),
                    ('Micka', 'AVAILABLE', 2),
                    ('Tweety', 'SOLD', 3)
                    """).execute();
        }
    }
}