from airium import Airium
from typing import List, Optional
from models import Pet, Category
from constants import Status, Css

class PetView:
    """Object-oriented HTML generator using Airium, mirroring Ujorm PetStore logic."""

    @staticmethod
    def render_page(pets: List[Pet], categories: List[Category], pet_to_edit: Optional[Pet] = None) -> str:
        a = Airium()
        a('<!DOCTYPE html>')
        with a.html(lang="en"):
            with a.head():
                a.meta(charset="utf-8")
                a.meta(name="viewport", content="width=device-width, initial-scale=1.0")
                a.title(_t="Python PetStore (Airium)")
                a.script(src="https://cdn.tailwindcss.com")
                a.link(href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap", rel="stylesheet")
                with a.style():
                    a("body { font-family: 'Inter', sans-serif; }")
            
            with a.body(klass="bg-gray-50 text-gray-900 min-h-screen pb-20"):
                with a.div(klass="max-w-5xl mx-auto px-4 py-12"):
                    PetView._render_header(a)
                    PetView._render_table(a, pets)
                    PetView._render_form(a, categories, pet_to_edit)
        
        return str(a)

    @staticmethod
    def _render_header(a: Airium) -> None:
        """Renders the page header similar to renderHeader in Java."""
        with a.header(klass="flex flex-col md:flex-row md:items-center justify-between mb-12 border-b border-gray-200 pb-8"):
            with a.div():
                a.h1(_t="Python PetStore", klass="text-4xl font-extrabold text-blue-600 tracking-tight mb-2")
                a.p(_t="Generated by Airium (Python Objects)", klass="text-gray-500 text-lg")
            with a.div(klass="mt-6 md:mt-0"):
                a.img(src="https://picsum.photos/seed/airiumpet/150/150", alt="PetStore Logo", 
                      klass="w-24 h-24 rounded-2xl shadow-sm border border-gray-200")

    @staticmethod
    def _render_table(a: Airium, pets: List[Pet]) -> None:
        """Renders the table of available pets similar to renderTable in Java."""
        with a.div(klass="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden mb-12"):
            with a.div(klass="px-6 py-4 border-b border-gray-200 bg-gray-50/50"):
                a.h2(_t="Available Pets", klass="text-xl font-bold text-gray-800")
            
            with a.div(klass="overflow-x-auto"):
                with a.table(klass="w-full text-left"):
                    with a.thead(klass="bg-gray-50 text-gray-500 text-xs uppercase tracking-wider font-semibold"):
                        with a.tr():
                            a.th(_t="ID", klass="px-6 py-4")
                            a.th(_t="Name", klass="px-6 py-4")
                            a.th(_t="Status", klass="px-6 py-4")
                            a.th(_t="Category", klass="px-6 py-4")
                            a.th(_t="Actions", klass="px-6 py-4 text-right")
                    
                    with a.tbody(klass="divide-y divide-gray-100"):
                        for pet in pets:
                            with a.tr(klass="hover:bg-gray-50/80 transition-colors"):
                                a.td(_t=f"#{pet.id}", klass="px-6 py-4 text-gray-400 font-mono text-sm")
                                a.td(_t=pet.name, klass="px-6 py-4 font-semibold text-gray-800")
                                with a.td(klass="px-6 py-4"):
                                    PetView._render_status_badge(a, pet.status)
                                a.td(_t=(pet.category.name if pet.category else ''), klass="px-6 py-4 text-gray-600")
                                with a.td(klass="px-6 py-4 text-right"):
                                    PetView._render_actions(a, pet)

    @staticmethod
    def _render_status_badge(a: Airium, status: Status) -> None:
        """Renders status badge."""
        base_klass: str = "px-2.5 py-0.5 rounded-full text-xs font-medium border "
        if status == Status.AVAILABLE:
            klass = base_klass + "bg-green-100 text-green-800 border-green-200"
        elif status == Status.PENDING:
            klass = base_klass + "bg-yellow-100 text-yellow-800 border-yellow-200"
        else:
            klass = base_klass + "bg-gray-100 text-gray-800 border-gray-200"
        
        a.span(_t=status.value.capitalize(), klass=klass)

    @staticmethod
    def _render_actions(a: Airium, pet: Pet) -> None:
        """Renders action buttons (Buy, Edit, Delete)."""
        with a.div(klass="flex justify-end gap-2"):
            # Buy button
            with a.form(action=f"/pets/{pet.id}/buy", method="POST", klass="inline"):
                buy_attr = {"type": "submit"}
                if pet.status != Status.AVAILABLE:
                    buy_attr["disabled"] = "disabled"
                
                a.button(_t="Buy", **buy_attr, 
                         klass="px-3 py-1.5 rounded-lg bg-green-500 text-white text-sm font-medium hover:bg-green-600 disabled:opacity-50 disabled:cursor-not-allowed transition-all")
            
            # Edit button
            a.a(_t="Edit", href=f"/?action=edit&pet_id={pet.id}", 
                klass="px-3 py-1.5 rounded-lg border border-gray-200 hover:border-blue-400 hover:text-blue-600 text-gray-600 text-sm font-medium transition-all")
            
            # Delete button
            with a.form(action=f"/pets/{pet.id}/delete", method="POST", klass="inline"):
                a.button(_t="Delete", type="submit", 
                         klass="px-3 py-1.5 rounded-lg border border-gray-200 hover:border-red-400 hover:text-red-600 text-gray-400 text-sm font-medium transition-all")

    @staticmethod
    def _render_form(a: Airium, categories: List[Category], pet_to_edit: Optional[Pet] = None) -> None:
        """Renders the input form."""
        with a.section(id="pet-form", klass="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden"):
            with a.div(klass="px-6 py-4 border-b border-gray-200 bg-gray-50/50 flex justify-between items-center"):
                a.h2(_t=('Update Pet' if pet_to_edit else 'Register New Pet'), klass="text-xl font-bold text-gray-800")
                if pet_to_edit:
                    a.a(_t="Clear", href="/", klass="text-xs text-blue-600 hover:underline")
            
            with a.form(action="/pets", method="POST", klass="p-6"):
                if pet_to_edit:
                    a.input(type="hidden", name="id", value=str(pet_to_edit.id))
                
                with a.div(klass="grid grid-cols-1 md:grid-cols-4 gap-6"):
                    with a.div(klass="md:col-span-1"):
                        a.label(_t="Pet Name", klass="block text-sm font-semibold text-gray-700 mb-2")
                        a.input(type="text", name="name", value=(pet_to_edit.name if pet_to_edit else ''), 
                                placeholder="e.g. Rex", required="required",
                                klass="block w-full px-4 py-2.5 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-all font-medium text-gray-800")
                    
                    with a.div():
                        a.label(_t="Status", klass="block text-sm font-semibold text-gray-700 mb-2")
                        with a.select(name="status", klass="block w-full px-4 py-2.5 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-all font-medium text-gray-800"):
                            for s in Status:
                                opt_attr = {"value": s.value}
                                if pet_to_edit and pet_to_edit.status == s:
                                    opt_attr["selected"] = "selected"
                                a.option(_t=s.value.capitalize(), **opt_attr)
                    
                    with a.div():
                        a.label(_t="Category", klass="block text-sm font-semibold text-gray-700 mb-2")
                        with a.select(name="category_id", klass="block w-full px-4 py-2.5 rounded-xl border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 transition-all font-medium text-gray-800"):
                            for cat in categories:
                                opt_attr = {"value": str(cat.id)}
                                if pet_to_edit and pet_to_edit.category_id == cat.id:
                                    opt_attr["selected"] = "selected"
                                a.option(_t=cat.name, **opt_attr)
                    
                    with a.div(klass="flex items-end"):
                        a.button(_t=('Update' if pet_to_edit else 'Register'), type="submit",
                                 klass="w-full h-11 flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl shadow-lg shadow-blue-500/20 active:scale-95 transition-all")
