CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE pet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL,
    category_id BIGINT NOT NULL,
    CONSTRAINT fk_pet_category FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE pet_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    pet_id BIGINT NOT NULL,
    CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_pet FOREIGN KEY (pet_id) REFERENCES pet(id) ON DELETE CASCADE
);

-- Default test data
INSERT INTO category (name) VALUES ('Dogs'), ('Cats'), ('Birds');
INSERT INTO customer (id, name) VALUES (1, 'John Doe');

INSERT INTO pet (name, status, category_id) VALUES
    ('Rex', 'AVAILABLE', 1),
    ('Buddy', 'PENDING', 1),
    ('Micka', 'AVAILABLE', 2),
    ('Tweety', 'SOLD', 3);