# Log is switched off.
org.ujorm.logSqlLevel = FINEST

# Log parameters of the SQL statement.
org.ujorm.logSqlLevel.logSqlParams = true

# Enable quoting the SQL columns
_org.ujorm.enableSqlQuoting = true;

