package org.ujorm.petstore;

import org.ujorm.tools.jdbc.SqlBuilder;

import java.sql.Connection;

/** Initial database setup and schema generation */
public class DatabaseInitializer {

    /** Creates database tables if not already initialized */
    public void createTables(Connection connection) {
        try (var query = new SqlBuilder(connection)) {
            changeset_01(query);
        }
    }

    /** Executes DDL and initial DML scripts using standard SQL identity syntax */
    private void changeset_01(SqlBuilder query) {
        var tableExists = query.sql("""
                        SELECT 1 FROM information_schema.tables
                        WHERE LOWER(table_name) = 'employee'
                          AND LOWER(table_schema) = 'public'
                        FETCH FIRST 1 ROWS ONLY
                        """).toStream(rs -> rs)
                .findFirst()
                .isPresent();
        if (tableExists) {
            return;
        }

        query.sql("""
                CREATE TABLE employee (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL
                )
                """).execute();

        query.sql("""
                CREATE TABLE category (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL
                )
                """).execute();

        query.sql("""
                CREATE TABLE customer (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL
                )
                """).execute();

        query.sql("""
                CREATE TABLE pet (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL,
                    status VARCHAR(50) NOT NULL,
                    category_id BIGINT NOT NULL,
                    CONSTRAINT fk_pet_category FOREIGN KEY (category_id) REFERENCES category(id)
                )
                """).execute();

        query.sql("""
                CREATE TABLE pet_order (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id BIGINT NOT NULL,
                    pet_id BIGINT NOT NULL,
                    CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE CASCADE,
                    CONSTRAINT fk_order_pet FOREIGN KEY (pet_id) REFERENCES pet(id) ON DELETE CASCADE
                )
                """).execute();

        insertDataRows_01(query);
    }

    /** Insert Data */
    private void insertDataRows_01(SqlBuilder query) {
        query.sql("INSERT INTO category (name) VALUES (:name)");
        var dogsId = query.bind("name", "Dogs").executeInsert()
                .getGeneratedLastKey(rs -> rs.getLong(1));
        var catsId = query.bind("name", "Cats").executeInsert()
                .getGeneratedLastKey(rs -> rs.getLong(1));
        var birdsId = query.bind("name", "Birds").executeInsert()
                .getGeneratedLastKey(rs -> rs.getLong(1));

        query.sql("""
                        INSERT INTO pet (name, status, category_id) VALUES
                         ('Rex', 'AVAILABLE', :dogsId),
                         ('Buddy', 'PENDING', :dogsId),
                         ('Daisy', 'AVAILABLE', :catsId),
                         ('Tweety', 'SOLD', :birdsId)
                        """)
                .bind("dogsId", dogsId)
                .bind("catsId", catsId)
                .bind("birdsId", birdsId)
                .execute();
    }
}