package org.ujorm.petstore;

import org.ujorm.orm.core.EntityManager;
import org.ujorm.orm.utils.EntityContext;
import org.ujorm.petstore.Constants.Status;
import org.ujorm.petstore.Entities.Category;
import org.ujorm.petstore.Entities.Customer;
import org.ujorm.petstore.Entities.Pet;
import org.ujorm.orm.SqlQuery;

import java.sql.Connection;

/** Initial database setup and schema generation */
public class DatabaseInitializer {

    private static final EntityContext CTX = EntityContext.ofDefault();
    private static final EntityManager<Category, Long> CATEGORY_EM = CTX.entityManager(Category.class);
    private static final EntityManager<Customer, Long> CUSTOMER_EM = CTX.entityManager(Customer.class);
    private static final EntityManager<Pet, Long> PET_EM = CTX.entityManager(Pet.class);

    /** Creates database tables if not already initialized */
    public void createTables(Connection connection) {
        try (var query = new SqlQuery(connection)) {
            changeset_01(query, connection);
        }
    }

    /** Executes DDL and initial DML scripts using standard SQL identity syntax */
    private void changeset_01(SqlQuery query, Connection connection) {
        var tableExists = query.sql("""
                        SELECT 1 FROM information_schema.tables
                        WHERE LOWER(table_name) = 'employee'
                          AND LOWER(table_schema) = 'public'
                        FETCH FIRST 1 ROWS ONLY
                        """).toStream(rs -> rs)
                .findFirst()
                .isPresent();
        if (tableExists) {
            return;
        }

        query.sql("""
                CREATE TABLE employee (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL
                )
                """).execute();

        query.sql("""
                CREATE TABLE category (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL
                )
                """).execute();

        query.sql("""
                CREATE TABLE customer (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL
                )
                """).execute();

        query.sql("""
                CREATE TABLE pet (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL,
                    status VARCHAR(50) NOT NULL,
                    category_id BIGINT NOT NULL,
                    CONSTRAINT fk_pet_category FOREIGN KEY (category_id) REFERENCES category(id)
                )
                """).execute();

        query.sql("""
                CREATE TABLE pet_order (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id BIGINT NOT NULL,
                    pet_id BIGINT NOT NULL,
                    CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE CASCADE,
                    CONSTRAINT fk_order_pet FOREIGN KEY (pet_id) REFERENCES pet(id) ON DELETE CASCADE
                )
                """).execute();

        insertDataRows_01(connection);
    }

    /** Inserts the initial demo data using entity objects and the {@link EntityManager}. */
    private void insertDataRows_01(Connection connection) {
        var categoryCrud = CATEGORY_EM.crud(connection);
        var dogs = categoryCrud.insert(new Category(null, "Dogs"));
        var cats = categoryCrud.insert(new Category(null, "Cats"));
        var birds = categoryCrud.insert(new Category(null, "Birds"));
        CUSTOMER_EM.crud(connection).insert(new Customer(null, "Demo guest"));

        var petCrud = PET_EM.crud(connection);
        petCrud.insert(new Pet(null, "Rex", Status.AVAILABLE, dogs));
        petCrud.insert(new Pet(null, "Buddy", Status.PENDING, dogs));
        petCrud.insert(new Pet(null, "Daisy", Status.AVAILABLE, cats));
        petCrud.insert(new Pet(null, "Tweety", Status.SOLD, birds));
    }
}